/* AuraTrade desk launcher — shell cache. Generated by scripts/make-desk-link.mjs. */
var CACHE = 'auratrade-desk-shell-v2';
var SHELL = ['./', './index.html', './manifest.webmanifest', './icon.svg', './icon-512.png'];

self.addEventListener('install', function (e) {
  // One missing file must not fail the whole install, or the worker never
  // activates and the cache this exists for is never written.
  e.waitUntil(caches.open(CACHE).then(function (c) {
    return Promise.all(SHELL.map(function (u) { return c.add(u)['catch'](function () {}); }));
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.map(function (k) { return k === CACHE ? null : caches['delete'](k); }));
  }).then(function () { return self.clients.claim(); }));
});

/** Cheap first: GitHub Pages sends an ETag, so bodies are read only without one. */
function tagOf(r) { return (r.headers.get('etag') || r.headers.get('last-modified') || ''); }
function differs(served, published) {
  var a = tagOf(served), b = tagOf(published);
  if (a && b) return Promise.resolve(a !== b);
  return Promise.all([served.clone().text(), published.clone().text()])
    .then(function (t) { return t[0] !== t[1]; }, function () { return false; });
}
function announce() {
  self.clients.matchAll({ type: 'window' }).then(function (cs) {
    cs.forEach(function (c) { try { c.postMessage({ auratrade: 'shell-updated' }); } catch (e) {} });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  // THE DESK IS NEVER CACHED. Anything not served from this origin — every
  // tunnel address, every beacon store — is left entirely alone.
  if (new URL(req.url).origin !== self.location.origin) return;
  var isPage = req.mode === 'navigate' || req.destination === 'document';
  e.respondWith(caches.open(CACHE).then(function (c) {
    return c.match(req, { ignoreSearch: true }).then(function (hit) {
      // Cloned BEFORE the hit is handed over: once a body has gone to
      // respondWith it cannot be read again, and the comparison needs it.
      var served = hit ? hit.clone() : null;
      var live = fetch(req).then(function (res) {
        if (!res || !res.ok) return hit || res;
        var published = res.clone();
        c.put(req, res.clone());
        // Only a page swap is worth a reload; a changed icon is not.
        if (served && isPage) differs(served, published).then(function (yes) { if (yes) announce(); });
        return res;
      })['catch'](function () { return hit; });
      // Kept alive explicitly: on a cache hit the response returns at once, and
      // without this the worker can be shut down mid-revalidate — which is how
      // a shell cache quietly stops ever updating.
      e.waitUntil(live);
      return hit || live;
    });
  }));
});
