/* AuraTrade desk launcher — shell cache. Generated by scripts/make-desk-link.mjs. */
var CACHE = 'auratrade-desk-shell-v9';
var SHELL = ['./', './index.html', './mobile.html', './mobile-desk.html', './mobile-desk-v2.html', './mobile-desk-v3.html', './mobile-desk-v4.html', './manifest.webmanifest', './icon.svg', './icon-512.png'];

self.addEventListener('install', function (e) {
  // One missing file must not fail the whole install, or the worker never
  // activates and the cache this exists for is never written.
  e.waitUntil(caches.open(CACHE).then(function (c) {
    return Promise.all(SHELL.map(function (u) { return c.add(u)['catch'](function () {}); }));
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.map(function (k) { return k === CACHE ? null : caches['delete'](k); }));
  }).then(function () { return self.clients.claim(); }));
});

var PAGE_DEADLINE_MS = 2500;
var MOBILE_PAGE_DEADLINE_MS = 350;

function fromCache(req) {
  return caches.open(CACHE).then(function (c) { return c.match(req, { ignoreSearch: true }); });
}
function keep(req, res) {
  if (!res || !res.ok) return Promise.resolve();
  var copy = res.clone();
  return caches.open(CACHE).then(function (c) { return c.put(req, copy); })['catch'](function () {});
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  // THE DESK IS NEVER CACHED. Anything not served from this origin — every
  // tunnel address, every beacon store — is left entirely alone.
  if (new URL(req.url).origin !== self.location.origin) return;

  if (req.mode === 'navigate' || req.destination === 'document') {
    // The page: newest wins, with the cache behind it and a deadline in front.
    var deadline = /[/]mobile[.]html$/.test(new URL(req.url).pathname) ? MOBILE_PAGE_DEADLINE_MS : PAGE_DEADLINE_MS;
    var storageWork = Promise.resolve();
    var net = fetch(req).then(function (res) { if (!res.ok) throw new Error('HTTP ' + res.status); storageWork = keep(req, res); return res; });
    var late = new Promise(function (_, reject) {
      setTimeout(function () { reject(new Error('slow')); }, deadline);
    });
    e.respondWith(Promise.race([net, late])['catch'](function () {
      // The same request, not a second one — reusing net means a network that
      // is merely slow still ends up in the cache for next time.
      return fromCache(req).then(function (hit) { return hit || net; });
    }));
    /**
     * AND THE WORKER IS HELD OPEN UNTIL THE STORE FINISHES.
     *
     * respondWith only keeps it alive until the RESPONSE settles, and on a
     * fast network that is long before c.put() has written anything. Without
     * this line the shell was never actually stored — measured 2026-09-12
     * against a poisoned cache: the network copy was served correctly and the
     * cache still held the old one afterwards, which would have left the
     * offline fallback, the entire reason this worker exists, not working.
     */
    e.waitUntil(net.then(function () { return storageWork; })['catch'](function () {}));
    return;
  }

  // Everything else — icons, the manifest — is cache-first and refreshed
  // behind. They change about once a year and cost a phone's data every load.
  e.respondWith(fromCache(req).then(function (hit) {
    var live = fetch(req).then(function (res) { return keep(req, res).then(function () { return res; }); })['catch'](function () { return hit; });
    if (!hit) return live;
    e.waitUntil(live);
    return hit;
  }));
});
